// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Azure.Containers.ContainerRegistry.Models
{
    [CodeGenModel("ManifestWrapper")]
    internal partial class Manifest
    {

        // TODO: add appropriate constructors

        /// <summary> Media type for this Manifest. </summary>
        public string MediaType { get; set; }

        /// <summary> (ManifestList, OCIIndex) List of V2 image layer information. </summary>
        public IList<ManifestListAttributes> Manifests { get; }

        /// <summary> (V2, OCI) Image config descriptor. </summary>
        public Descriptor Config { get; set; }

        /// <summary> (V2, OCI) List of V2 image layer information. </summary>
        public IList<Descriptor> Layers { get; }

        /// <summary> (OCI, OCIIndex) Additional metadata. </summary>
        public Annotations Annotations { get; set; }

    }
}
